---
- name: Create "docker" group
  ansible.builtin.group:
   name: docker
   state: present

- name: Add remote "ubuntu" user to "docker" group
  ansible.builtin.user:
   name: ubuntu
   group: docker
   append: true

# https://serverfault.com/a/930806
- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection
...
