---
- name: Update apt repository
  apt:
    update_cache: yes

- name: Install packages on Ubuntu 
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - ca-certificates
  - curl
  - gnupg
  - python3-pip

- name: Install Docker module for Python
  pip:
    name: "{{ item }}"
  with_items:
  - docker
  - docker-compose

- name: Add docker gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the APT repo for docker engine
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: true

- name: Install Docker CE engine 
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-compose-plugin

...
